iter_num: &iter_num 100
device: &device cuda:0
reloc_coef: 0.5

data_path: ./data/test_500_10/
#data_path: ./data/test_1000_20/
#data_path: ./data/test_30_1/
#data_path: ./casedata/test_100_1/


methods:
  Gurobi:
    run_fn: run_gurobi_reloc
    OutputFlag: 0
    MIPGap: 0

  Greedy-reloc:
    run_fn: run_greedy_reloc
    iter_num:  *iter_num

  # Greedy-filter:
  #   run_fn: run_greedy_filter_reloc
  #   init_num: *iter_num



  PPO-swap:
    run_fn: run_ppo_reloc
    iter_num: *iter_num

    ckpt: ./logs/20260124-154826/checkpoints/epoch=286-step=4592.ckpt
    name: ppo_swap_test
    device: *device

  # PPO-filter:
  #   run_fn: run_ppo_filter_reloc
  #   iter_num: *iter_num

  #   ckpt: ./logs/20260124-154826/checkpoints/epoch=286-step=4592.ckpt
  #   name: ppo_swap_test
  #   device: *device
