iter_num: &iter_num 30
device: &device cuda:0
reloc_coef: 0.6

#data_path: ./data/test_100_20/
data_path: ./data/test_1000_20/
#data_path: ./data/test_100_20/


methods:
  Gurobi:
    run_fn: run_gurobi_reloc
    OutputFlag: 0
    MIPGap: 0

  # Greedy-swap:
  #   run_fn: run_greedy_swap_reloc
  #   iter_num: *iter_num

  # Random-swap:
  #   run_fn: run_random_swap_reloc
  #   iter_num: *iter_num

  # BestResponse:
  #   iter_num: *iter_num
  #   run_fn: run_br

  # FR2FP:
  #   run_fn: run_FR2FP

  PPO-swap:
    run_fn: run_ppo_swap_reloc
    iter_num: *iter_num
    #ckpt: ./logs/20260106-010525/checkpoints/epoch=211-step=3392.ckpt  #100 "range(5, 10)"
    ckpt: ./logs/20260106-061223/checkpoints/epoch=230-step=3696.ckpt  #100 "range(5, 10)"
    
 

    name: ppo_swap_test
    device: *device
