init_num: &init_num 10
iter_num: &iter_num 30
swap_num: &swap_num null
device: &device cuda:0

data_path: ./casedata/test_100_1/
#data_path: ./data/test_100_19/
# data_path: ./data/test_200_20/
#data_path: ./casedata/test_100_1/

methods:
  Gurobi:
    run_fn: run_gurobi
    OutputFlag: 0
    MIPGap: 0

  Greedy-swap:
    run_fn: run_greedy_swap
    init_num: *init_num
    swap_num: *swap_num

  # Random-swap:
  #   run_fn: run_random_swap
  #   init_num: *init_num
  #   iter_num: *iter_num
  #   swap_num: *swap_num

  # SA:
  #   run_fn: run_SA
  #   iter_num: 1000
  #   initial_temp: 10000
  #   cooling_rate: 0.99

  # Maranzana:
  #   run_fn: run_maranzana
  #   iter_num: *iter_num
  #   swap_num: *swap_num

  PPO-swap:
    run_fn: run_ppo_swap
    init_num: *init_num
    iter_num: *iter_num
    swap_num: *swap_num
    
    #ckpt: ./logs/20260106-061223/checkpoints/epoch=230-step=3696.ckpt  #100 "range(5, 26,5)"  swap_env
    #ckpt: ./logs/20260121-101927/checkpoints/epoch=284-step=4560.ckpt  #100 "range(5, 10)"
    # ckpt: ./logs/20260121-100822/checkpoints/epoch=66-step=1072.ckpt  #100 "range(5, 10)"
    #ckpt: ./logs/20260121-154345/checkpoints/epoch=61-step=992.ckpt
    ckpt: ./logs/20260122-223736/checkpoints/epoch=173-step=2784.ckpt
    name: ppo_swap_test
    device: *device
