init_num: &init_num 15  #调高效果好
iter_num: &iter_num 5
# init_num: &init_num 2
# iter_num: &iter_num 2
swap_num: &swap_num null
device: &device cuda:0

#data_path: ./casedata/test_100_1/
#data_path: ./data/test_100_19/
data_path: ./data/test_200_20/
#data_path: ./casedata/test_100_1/

methods:
  Gurobi:
    run_fn: run_gurobi
    OutputFlag: 0
    MIPGap: 0

  Greedy-swap:
    run_fn: run_greedy_swap
    init_num: *init_num
    swap_num: *swap_num

  Greedy-filter:
    run_fn: run_greedy_filter
    init_num: *init_num
    swap_num: *swap_num

  # Random-swap:
  #   run_fn: run_random_swap
  #   init_num: *init_num
  #   iter_num: *iter_num
  #   swap_num: *swap_num

  # SA:
  #   run_fn: run_SA
  #   iter_num: 1000
  #   initial_temp: 10000
  #   cooling_rate: 0.99

  # Maranzana:
  #   run_fn: run_maranzana
  #   iter_num: *iter_num
  #   swap_num: *swap_num

  PPO-swap:
    run_fn: run_ppo_swap
    init_num: *init_num
    iter_num: *iter_num
    swap_num: *swap_num

    # ckpt: ./logs/20260122-223736/checkpoints/epoch=173-step=2784.ckpt #ppo
    
    ckpt: ./logs/20260202-094055/checkpoints/epoch=274-step=4400.ckpt #ppo_lx5
    # ckpt: ./logs/20260131-134620/checkpoints/epoch=284-step=4560.ckpt #ppo_lx3

    name: ppo_swap_test
    device: *device

  PPO-filter:
    run_fn: run_ppo_filter
    init_num: *init_num
    iter_num: *iter_num
    swap_num: *swap_num
    
    # ckpt: ./logs/20260122-223736/checkpoints/epoch=173-step=2784.ckpt #ppo
    
    ckpt: ./logs/20260202-094055/checkpoints/epoch=274-step=4400.ckpt #ppo_lx5
    # ckpt: ./logs/20260131-134620/checkpoints/epoch=284-step=4560.ckpt #ppo_lx3
    name: ppo_swap_test
    device: *device


  

